### ISSUE TITLE
Unexpected behaviors of design code (.NET)

### ISSUE THREAD

**Issue by junjieim** [arup-group/oasys-api-samples#19]
All the code following is modified on the sample file of `ApiToAds.cs`.

# Only add reinforcement

When I only add the reinforcement into the code, it works as expected:

```C#
using System;
using Oasys.AdSec;
using Oasys.AdSec.IO.Serialization;
using Oasys.Collections;
using Oasys.AdSec.Materials;
using Oasys.AdSec.StandardMaterials;
using Oasys.Profiles;
using OasysUnits;
using Oasys.AdSec.DesignCode;
using Oasys.AdSec.Reinforcement.Layers; // new import
using Oasys.AdSec.Reinforcement.Groups; // new import
using Oasys.AdSec.Reinforcement;        // new import

namespace ApiToAds
{
    /// <summary>
    /// This example shows how to convert an API object into .ads file
    ///
    /// You might like to run the 'ApiVersion' example first, just to check
    /// that the API is installed correctly.
    /// </summary>
    public static class ApiToAds
    {
        public static void Main()
        {
            // Create API section 
            IConcrete C30 = Concrete.EN1992.Part1_1.Edition_2004.NationalAnnex.GB.PD6687.Edition_2010.C30_37;
            ICircleProfile circle_profile = ICircleProfile.Create(Length.FromMillimeters(1000));
            ISection section = ISection.Create(circle_profile, C30);

            // New code here ////////////////////////////////////////////////////////////////////////////
            IReinforcement reinforcementMaterial = Reinforcement.Steel.EN1992.Part1_1.Edition_2004.NationalAnnex.GB.Edition_2014.S500B;
            ILayer layer = ILayerByBarCount.Create(4, IBarBundle.Create(reinforcementMaterial, Length.FromMillimeters(32)));
            // Set some reinforcement
            IGroup group = ILineGroup.Create(
                IPoint.Create(Length.Zero, Length.Zero),
                IPoint.Create(Length.FromMillimeters(150), Length.FromMillimeters(150)),
                layer);

            section.ReinforcementGroups.Add(group);
            ////////////////////////////////////////////////////////////////////////////////////////////

            // Use JsonConverter's SectionToJson method to obtain the JSON string 
            JsonConverter converter = new JsonConverter(EN1992.Part1_1.Edition_2004.NationalAnnex.GB.PD6687.Edition_2010);
            String json = converter.SectionToJson(section);

            // Save this JSON string into .ads file 
            System.IO.File.WriteAllText("adsec_section.ads", json);

            // To save a section with loads (or deformation) 
            Oasys.AdSec.ILoad load_one = ILoad.Create(Force.FromKilonewtons(-10), Moment.Zero, Moment.Zero);
            Oasys.AdSec.ILoad load_two = ILoad.Create(Force.FromKilonewtons(-15), Moment.Zero, Moment.Zero);
            Oasys.Collections.IList<ILoad> load_list = Oasys.Collections.IList<ILoad>.Create();
            load_list.Add(load_one);
            load_list.Add(load_two);
            String json_with_loads = converter.SectionToJson(section, load_list);
            System.IO.File.WriteAllText("adsec_section_with_loads.ads", json_with_loads);

        }
    }
}
```

# change the design code

But once I change the design code, errors come out.

```C#
using System;
using Oasys.AdSec;
using Oasys.AdSec.IO.Serialization;
using Oasys.Collections;
using Oasys.AdSec.Materials;
using Oasys.AdSec.StandardMaterials;
using Oasys.Profiles;
using OasysUnits;
using Oasys.AdSec.DesignCode;
using Oasys.AdSec.Reinforcement.Layers; // new import
using Oasys.AdSec.Reinforcement.Groups; // new import
using Oasys.AdSec.Reinforcement;        // new import

namespace ApiToAds
{
    /// <summary>
    /// This example shows how to convert an API object into .ads file
    ///
    /// You might like to run the 'ApiVersion' example first, just to check
    /// that the API is installed correctly.
    /// </summary>
    public static class ApiToAds
    {
        public static void Main()
        {
            // Create API section 
            //IConcrete C30 = Concrete.EN1992.Part1_1.Edition_2004.NationalAnnex.GB.PD6687.Edition_2010.C30_37
            IConcrete C30 = Concrete.HK.CP.Edition_2013.C30;                        // change design code here ////////////////
            ICircleProfile circle_profile = ICircleProfile.Create(Length.FromMillimeters(1000));
            ISection section = ISection.Create(circle_profile, C30);

            // New code here ////////////////////////////////////////////////////////////////////////////
            IReinforcement reinforcementMaterial = Reinforcement.Steel.EN1992.Part1_1.Edition_2004.NationalAnnex.GB.Edition_2014.S500B;
            ILayer layer = ILayerByBarCount.Create(4, IBarBundle.Create(reinforcementMaterial, Length.FromMillimeters(32)));
            // Set some reinforcement
            IGroup group = ILineGroup.Create(
                IPoint.Create(Length.Zero, Length.Zero),
                IPoint.Create(Length.FromMillimeters(150), Length.FromMillimeters(150)),
                layer);

            section.ReinforcementGroups.Add(group);
            ////////////////////////////////////////////////////////////////////////////////////////////

            // Use JsonConverter's SectionToJson method to obtain the JSON string 
            //JsonConverter converter = new JsonConverter(EN1992.Part1_1.Edition_2004.NationalAnnex.GB.PD6687.Edition_2010);
            JsonConverter converter = new JsonConverter(HK.CP.Edition_2013);        // change design code here ////////////////
            String json = converter.SectionToJson(section);

            // Save this JSON string into .ads file 
            System.IO.File.WriteAllText("adsec_section.ads", json);

            // To save a section with loads (or deformation) 
            Oasys.AdSec.ILoad load_one = ILoad.Create(Force.FromKilonewtons(-10), Moment.Zero, Moment.Zero);
            Oasys.AdSec.ILoad load_two = ILoad.Create(Force.FromKilonewtons(-15), Moment.Zero, Moment.Zero);
            Oasys.Collections.IList<ILoad> load_list = Oasys.Collections.IList<ILoad>.Create();
            load_list.Add(load_one);
            load_list.Add(load_two);
            String json_with_loads = converter.SectionToJson(section, load_list);
            System.IO.File.WriteAllText("adsec_section_with_loads.ads", json_with_loads);

        }
    }
}
```

The error details:

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Oasys.AdSec.IO.Serialization.JsonConverter.SectionToJson(ISection section, IList`1 loads)
   at ApiToAds.ApiToAds.Main() in C:\Users\xx\source\refer\oasys-api-samples\AdSec\.NET\ApiToAds\ApiToAds.cs:line 47

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ValidationException: The section is invalid.
```
![image](https://github.com/arup-group/oasys-api-samples/assets/48527686/32267f9d-a61b-4d04-a929-dfc8bf0a816f)

**Comment by junjieim** [comment]
seems the reinforcement material should be the same with the design code.
